### ISSUE TITLE
Errors for modern API include stack

### ISSUE THREAD

**Issue by alan-agius4** [webpack-contrib/sass-loader#1068]
### Bug report
When using modern API, on errors stack traces are printed to the user.

### Actual Behavior

```
Error: Module build failed (from ./node_modules/sass-loader/dist/cjs.js):
SassError: Can't find stylesheet to import.
  ╷
1 │ @import "font-sawessome/scss/font-awesome"
  │         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  ╵
  src/app/styles.scss 1:9  root stylesheet
    at Object.<anonymous> (/usr/local/xxxxxxxxx/git/angular-cli/a/node_modules/css-loader/dist/cjs.js??ruleSet[1].rules[5].rules[0].oneOf[0].use[1]!/usr/local/xxxxxxxxx/git/angular-cli/a/node_modules/postcss-loader/dist/cjs.js??ruleSet[1].rules[5].rules[0].oneOf[0].use[2]!/usr/local/xxxxxxxxx/git/angular-cli/a/node_modules/resolve-url-loader/index.js??ruleSet[1].rules[5].rules[1].use[0]!/usr/local/xxxxxxxxx/git/angular-cli/a/node_modules/sass-loader/dist/cjs.js??ruleSet[1].rules[5].rules[1].use[1]!/usr/local/xxxxxxxxx/git/angular-cli/a/src/app/styles.scss:1:7)
    at /usr/local/xxxxxxxxx/git/angular-cli/a/node_modules/webpack/lib/javascript/JavascriptModulesPlugin.js:441:11
    at Hook.eval [as call] (eval at create (/usr/local/xxxxxxxxx/git/angular-cli/a/node_modules/tapable/lib/HookCodeFactory.js:19:10), <anonymous>:7:1)
    at Hook.CALL_DELEGATE [as _call] (/usr/local/xxxxxxxxx/git/angular-cli/a/node_modules/tapable/lib/Hook.js:14:14)
    at /usr/local/xxxxxxxxx/git/angular-cli/a/node_modules/webpack/lib/Compilation.js:5057:39
    at tryRunOrWebpackError (/usr/local/xxxxxxxxx/git/angular-cli/a/node_modules/webpack/lib/HookWebpackError.js:83:7)
    at __webpack_require_module__ (/usr/local/xxxxxxxxx/git/angular-cli/a/node_modules/webpack/lib/Compilation.js:5055:12)
    at __webpack_require__ (/usr/local/xxxxxxxxx/git/angular-cli/a/node_modules/webpack/lib/Compilation.js:5012:18)
    at /usr/local/xxxxxxxxx/git/angular-cli/a/node_modules/webpack/lib/Compilation.js:5083:20
    at symbolIterator (/usr/local/xxxxxxxxx/git/angular-cli/a/node_modules/neo-async/async.js:3485:9)

```
### Expected Behavior

```
Error: Module build failed (from ./node_modules/sass-loader/dist/cjs.js):
SassError: Can't find stylesheet to import.
  ╷
1 │ @import "font-sawessome/scss/font-awesome"
  │         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  ╵
  src/app/styles.scss 1:9  root stylesheet
```
### How Do We Reproduce?
- Config the sass-loader as follows;
```js
{
  loader: require.resolve('sass-loader'),
  options: {
    implementation: require('sass'),
    api: 'modern',
  },
}
```

Add a stylesheet that contains an errors such as an invalid import.
```scss
@import "font-sawessome/scss/font-awesome"
```
### Please paste the results of `npx webpack-cli info` here, and mention other relevant information
```
 System:
    OS: Linux 5.17 Debian GNU/Linux rodete 12 (rodete)
    CPU: (48) x64 AMD EPYC 7B12
    Memory: 152.19 GB / 188.89 GB
  Binaries:
    Node: 14.19.2 - ~/.nvm/versions/node/v14.19.2/bin/node
    Yarn: 1.22.17 - ~/.nvm/versions/node/v14.19.2/bin/yarn
    npm: 8.11.0 - ~/.nvm/versions/node/v14.19.2/bin/npm
  Browsers:
    Chrome: 103.0.5060.53
    Firefox: 91.10.0esr
```

**Comment by alexander-akait** [comment]
Yes, modern API is not wokring, because there are limitations on sass side, we need to fix them, don't know why it was design very bad

**Comment by alan-agius4** [comment]
@alexander-akait, I don't think this is a matter of bad design from sass-side. But rather there are 2 problems one on this loader side and bigger other one in Webpack itself. 

1. sass-loader  - hideError is not set unless `.formatted` is present on the Error object. `formatted` doesn't exist in the modern api. https://github.com/webpack-contrib/sass-loader/blob/5f0658efbd6fe0359ddc1633b73402c1609bf26a/src/SassError.js#L22-L32
2. webpack - When [`errorStack`](https://webpack.js.org/configuration/stats/#statserrorstack) to `false`, stacktraces are still appended to the error message as it appears that this flag is ignored and instead `hideStack` is taken into consideration
https://github.com/webpack/webpack/blob/e2f1592f7e4d8f0578e5bb23d6a863b4a2b5f309/lib/ModuleBuildError.js#L31-L32

**Comment by alexander-akait** [comment]
@alan-agius4 o you mean the problem in error reporting? Resolution in modern API is not work...

> sass-loader - hideError is not set unless .formatted is present on the Error object. formatted doesn't exist in the modern api.

Let fix it, should be easy, do you want to send a PR?

> webpack - When [errorStack](https://webpack.js.org/configuration/stats/#statserrorstack) to false, stacktraces are still appended to the error message as it appears that this flag is ignored and instead hideStack is taken into consideration
https://github.com/webpack/webpack/blob/e2f1592f7e4d8f0578e5bb23d6a863b4a2b5f309/lib/ModuleBuildError.js#L31-L32

Can you open an issue in webpack? I think it is bug, but yes, there is intreting problem, if we hide stacktrace using `hideStack`, errors in stats will not have `stacktrace`, but if we change `hideStack` to `true` it will be very spammy, but you will have stacktrace in stats... sounds like conflicting in logic, let's open an issue and think about it

**Comment by alan-agius4** [comment]
Yeah, I can do both. Probably in the next couple of days.
