### ISSUE TITLE
error

### ISSUE THREAD

**Issue by Fatimahadi786** [webpack-contrib/sass-loader#1153]
Hey there! If you need support, help, or advice then this is not the place to ask.
Please visit [GitHub Discussions](https://github.com/webpack/webpack/discussions) or [StackOverflow](https://stackoverflow.com/questions/tagged/webpack) instead.

**Comment by Fatimahadi786** [comment]
ERROR in ./src/main.scss (./node_modules/css-loader/dist/cjs.js??ruleSet[1].rules[1].oneOf[7].use[1]!./node_modules/postcss-loader/dist/cjs.js??ruleSet[1].rules[1].oneOf[7].use[2]!./node_modules/resolve-url-loader/index.js??ruleSet[1].rules[1].oneOf[7].use[3]!./node_modules/react-scripts/node_modules/sass-loader/dist/cjs.js??ruleSet[1].rules[1].oneOf[7].use[4]!./src/main.scss)
Module build failed (from ./node_modules/resolve-url-loader/index.js):
Error: resolve-url-loader: error processing CSS
  file://E:/FYP/frontend/src/main.scss:30:4: Missed semicolon
You tried to parse SCSS with the standard CSS parser; try again with the postcss-scss parser
  You tried to parse SCSS with the standard CSS parser; try again with the postcss-scss parser
    at encodeError (E:\FYP\frontend\node_modules\resolve-url-loader\index.js:287:12)
    at onFailure (E:\FYP\frontend\node_modules\resolve-url-loader\index.js:228:14)

**Comment by Fatimahadi786** [comment]
help
