### ISSUE TITLE
4.0.1 doesn't respect webpack resolve root

### ISSUE THREAD

**Issue by sgulseth** [webpack-contrib/sass-loader#278]
After upgrading to sass-loader 4.0.1 our build fails because of a "missing" sass-module in the root folder, works fine with 4.0.0.

sass-loader 4.0.1:
<details>

```
sch-bp-2733 :: vg/vglive/vglive-web ‹master› » ./node_modules/.bin/webpack -p
Hash: ef0e6af85921fef7875b
Version: webpack 1.13.1
Time: 32770ms
                 Asset     Size  Chunks             Chunk Names
         app.bundle.js   688 kB       0  [emitted]  app
      vglive.bundle.js   3.7 kB       1  [emitted]  vglive
    100sport.bundle.js  3.71 kB       2  [emitted]  100sport
     app.bundle.js.map  5.42 MB       0  [emitted]  app
  vglive.bundle.js.map  28.5 kB       1  [emitted]  vglive
100sport.bundle.js.map  28.5 kB       2  [emitted]  100sport
   [0] multi vglive 28 bytes {1} [built]
   [0] multi app 28 bytes {0} [built]
   [0] multi 100sport 28 bytes {2} [built]
    + 735 hidden modules

ERROR in ./~/css-loader?sourceMap&-autoprefixer!./~/postcss-loader!./~/sass-loader?sourceMap!./src/sass/sites/vglive.scss
Module build failed:
@import "variables.scss";
       ^
      Error: Could not import variables.scss from any of the following locations:
  /Users/singulse/development/vg/vglive/vglive-web/src/sass/sites/variables.scss
  /Users/singulse/development/vg/vglive/vglive-web/src/sass/sites/_variables.scss
      in /Users/singulse/development/vg/vglive/vglive-web/src/sass/sites/vglive.scss (line 1, column 9)
 @ ./src/sass/sites/vglive.scss 4:14-211

ERROR in ./~/css-loader?sourceMap&-autoprefixer!./~/postcss-loader!./~/sass-loader?sourceMap!./src/sass/sites/100sport.scss
Module build failed:
@import "variables.scss";
       ^
      Error: Could not import variables.scss from any of the following locations:
  /Users/singulse/development/vg/vglive/vglive-web/src/sass/sites/variables.scss
  /Users/singulse/development/vg/vglive/vglive-web/src/sass/sites/_variables.scss
      in /Users/singulse/development/vg/vglive/vglive-web/src/sass/sites/100sport.scss (line 1, column 9)
 @ ./src/sass/sites/100sport.scss 4:14-213
```

</details>

sass-loader 4.0.0:
<details>

```
sch-bp-2733 :: vg/vglive/vglive-web ‹master› » npm i sass-loader@4.0.0
- async@2.0.1 node_modules/sass-loader/node_modules/async
vglive-web@1.0.0 /Users/singulse/development/vg/vglive/vglive-web
├── loud-rejection@1.4.1
└── sass-loader@4.0.0

npm WARN enoent ENOENT: no such file or directory, open '/Users/singulse/development/vg/vglive/vglive-web/src/js/package.json'
sch-bp-2733 :: vg/vglive/vglive-web ‹master*› » ./node_modules/.bin/webpack -p
Hash: 81e2a5a725a573bbe0ff
Version: webpack 1.13.1
Time: 37026ms
                 Asset     Size  Chunks             Chunk Names
         app.bundle.js   688 kB       0  [emitted]  app
      vglive.bundle.js   207 kB       1  [emitted]  vglive
    100sport.bundle.js   274 kB       2  [emitted]  100sport
     app.bundle.js.map  5.42 MB       0  [emitted]  app
  vglive.bundle.js.map   448 kB       1  [emitted]  vglive
100sport.bundle.js.map   583 kB       2  [emitted]  100sport
   [0] multi vglive 28 bytes {1} [built]
   [0] multi app 28 bytes {0} [built]
   [0] multi 100sport 28 bytes {2} [built]
    + 736 hidden modules
```

</details>

webpack.config.js
<details>

```
module.exports = {
    devtool: 'source-map',
    entry: {
        app: ['./src/js/app'],
        vglive: ['./src/sass/sites/vglive.scss'],
        '100sport': ['./src/sass/sites/100sport.scss']
    },
    output: {
        path: path.join(__dirname, 'public', 'js'),
        filename: '[name].bundle.js',
        publicPath: '/js'
    },
    resolve: {
        root: [
            path.resolve('./src/js'),
            path.resolve('./src/sass')
        ],
        extensions: ['', '.js', '.jsx', '.scss']
    },
    module: {
        loaders: [
            {
                test: /\.js$/,
                loaders: ['react-hot', 'babel'],
                include: path.join(__dirname, 'src', 'js'),
                exclude: /node_modules/
            },
            {
                test: /\.scss$/,
                include: path.join(__dirname, 'src', 'sass'),
                loaders: ['style', 'css?sourceMap&-autoprefixer', 'postcss', 'sass?sourceMap']
            }
        ]
    },
    postcss: [ autoprefixer({ browsers: browserSupport }) ],
    sassLoader: eyeglass({
        eyeglass: {
            root: path.join(__dirname, 'src', 'sass')
        }
    }),
    plugins: [
        new webpack.ContextReplacementPlugin(/moment[\/\\]locale$/, new RegExp(config.language)),
        new webpack.DefinePlugin({
            'process.env': {
                NODE_ENV: JSON.stringify(env)
            }
        })
    ]
};
```

</details>

**Comment by evilebottnawi** [comment]
@sgulseth please update to latest `sass-loader` version :+1: 

Closing this out, please feel free to reopen if this doesn't resolve your issue. Thanks!

**Comment by lengjh** [comment]
ERROR in ./node_modules/css-loader!./node_modules/sass-loader/lib/loader.js!./src/common.scss
Module build failed: Error: ENOENT: no such file
or directory, scandir 'E:\study\webpack4x\node_modules\node-sass\vendor'
    at Object.fs.readdirSync (fs.js:904:18)
    at Object.getInstalledBinaries (E:\study\webpack4x\node_modules\node-sass\lib\extensions.js:128:13)
    at foundBinariesList (E:\study\webpack4x\node_modules\node-sass\lib\errors.js:20:15)
    at foundBinaries (E:\study\webpack4x\node_modules\node-sass\lib\errors.js:15:5)
    at Object.module.exports.missingBinary (E:\study\webpack4x\node_modules\node-sass\lib\errors.js:45:5)
    at module.exports (E:\study\webpack4x\node_modules\node-sass\lib\binding.js:15:30)
    at Object.<anonymous> (E:\study\webpack4x\node_modules\node-sass\lib\index.js:14:35)
    at Module._compile (E:\study\webpack4x\node_modules\v8-compile-cache\v8-compile-cache.js:178:30)
    at Object.Module._extensions..js (module.js:654:10)
    at Module.load (module.js:556:32)
    at tryModuleLoad (module.js:499:12)
    at Function.Module._load (module.js:491:3)
    at Module.require (module.js:587:17)
    at require (E:\study\webpack4x\node_modules\v8-compile-cache\v8-compile-cache.js:159:20)
    at Object.<anonymous> (E:\study\webpack4x\node_modules\sass-loader\lib\loader.js:3:14)
    at Module._compile (E:\study\webpack4x\node_modules\v8-compile-cache\v8-compile-cache.js:178:30)
    at Object.Module._extensions..js (module.js:654:10)
    at Module.load (module.js:556:32)
    at tryModuleLoad (module.js:499:12)
    at Function.Module._load (module.js:491:3)
    at Module.require (module.js:587:17)
    at require (E:\study\webpack4x\node_modules\v8-compile-cache\v8-compile-cache.js:159:20)
    at loadLoader (E:\study\webpack4x\node_modules\loader-runner\lib\loadLoader.js:13:17)
    at iteratePitchingLoaders (E:\study\webpack4x\node_modules\loader-runner\lib\LoaderRunner.js:169:2)
    at iteratePitchingLoaders (E:\study\webpack4x\node_modules\loader-runner\lib\LoaderRunner.js:165:10)
    at E:\study\webpack4x\node_modules\loader-runner\lib\LoaderRunner.js:173:18
    at loadLoader (E:\study\webpack4x\node_modules\loader-runner\lib\loadLoader.js:36:3)
    at iteratePitchingLoaders (E:\study\webpack4x\node_modules\loader-runner\lib\LoaderRunner.js:169:2)
    at runLoaders (E:\study\webpack4x\node_modules\loader-runner\lib\LoaderRunner.js:362:2)
    at NormalModule.doBuild (E:\study\webpack4x\node_modules\webpack\lib\NormalModule.js:219:3)
    at NormalModule.build (E:\study\webpack4x\node_modules\webpack\lib\NormalModule.js:337:15)
    at Compilation.buildModule (E:\study\webpack4x\node_modules\webpack\lib\Compilation.js:346:10)
    at factory.create (E:\study\webpack4x\node_modules\webpack\lib\Compilation.js:572:15)
    at factory (E:\study\webpack4x\node_modules\webpack\lib\NormalModuleFactory.js:366:6)
    at hooks.afterResolve.callAsync (E:\study\webpack4x\node_modules\webpack\lib\NormalModuleFactory.js:143:13)
    at AsyncSeriesWaterfallHook.eval [as callAsync] (eval at create (E:\study\webpack4x\node_modules\tapable\lib\HookCodeFactory.js:24:12), <anonymous>:6:1)
 @ ./src/common.scss 2:14-118
 @ ./src/index.js





config

rules: [{
			test: /\.scss$/,
			use: [{
				loader: "style-loader" // creates style nodes from JS strings
			}, {
				loader: "css-loader" // translates CSS into CommonJS
			}, {
				loader: "sass-loader" // compiles Sass to CSS
			}]
		}]
