### ISSUE TITLE
[6.0.4] importing files directly from scoped npm package (ModuleBuildError)

### ISSUE THREAD

**Issue by someok** [webpack-contrib/sass-loader#452]
My webpack config process right when use sass-loader 6.0.3, but when update to 6.0.4, throw this error:

```
ERROR in ./outline/style/_index.scss
Module build failed: ModuleBuildError: Module build failed:
@import "~@blueprintjs/core/src/common/resets";
^
      File to import not found or unreadable: ~@blueprintjs/core/src/common/resets.
Parent style sheet: /Users/wjx/MyFolder/Develop/MyWorkspace/blah-projects/projects/app/outline/style/_blueprint.scss
      in /Users/wjx/MyFolder/Develop/MyWorkspace/blah-projects/projects/app/outline/style/_blueprint.scss (line 7, column 1)
    at runLoaders (/Users/wjx/MyFolder/Develop/MyWorkspace/blah-projects/node_modules/webpack/lib/NormalModule.js:192:19)
    at /Users/wjx/MyFolder/Develop/MyWorkspace/blah-projects/node_modules/loader-runner/lib/LoaderRunner.js:364:11
    at /Users/wjx/MyFolder/Develop/MyWorkspace/blah-projects/node_modules/loader-runner/lib/LoaderRunner.js:230:18
    at context.callback (/Users/wjx/MyFolder/Develop/MyWorkspace/blah-projects/node_modules/loader-runner/lib/LoaderRunner.js:111:13)
    at Object.asyncSassJobQueue.push [as callback] (/Users/wjx/MyFolder/Develop/MyWorkspace/blah-projects/node_modules/sass-loader/lib/loader.js:57:13)
    at Object.<anonymous> (/Users/wjx/MyFolder/Develop/MyWorkspace/blah-projects/node_modules/async/dist/async.js:2243:31)
    at Object.callback (/Users/wjx/MyFolder/Develop/MyWorkspace/blah-projects/node_modules/async/dist/async.js:906:16)
    at options.error (/Users/wjx/MyFolder/Develop/MyWorkspace/blah-projects/node_modules/node-sass/lib/index.js:294:32)
 @ ./outline/index.js 6:0-29


    ERROR in /Users/wjx/MyFolder/Develop/MyWorkspace/blah-projects/~/css-loader?{"sourceMap":true}!/Users/wjx/MyFolder/Develop/MyWorkspace/blah-projects/~/postcss-loader/lib?{"sourceMap":true}!/Users/wjx/MyFolder/Develop/MyWorkspace/blah-projects/~/sass-loader/lib/loader.js?{"sourceMap":true,"outputStyle":"nested"}!./outline/style/_index.scss
    Module build failed:
    @import "~@blueprintjs/core/src/common/resets";
    ^
          File to import not found or unreadable: ~@blueprintjs/core/src/common/resets.
    Parent style sheet: /Users/wjx/MyFolder/Develop/MyWorkspace/blah-projects/projects/app/outline/style/_blueprint.scss
          in /Users/wjx/MyFolder/Develop/MyWorkspace/blah-projects/projects/app/outline/style/_blueprint.scss (line 7, column 1)

```

**Comment by michael-ciniawsky** [comment]
#450

**Comment by Maxouhell** [comment]
Could you publish 6.0.5 on npm please ?

**Comment by michael-ciniawsky** [comment]
@Maxouhell [v6.0.5](https://github.com/webpack-contrib/sass-loader/releases/tag/v6.0.5)

**Comment by rtrompier** [comment]
Can you please upload to the npm repository too ? 

Thanks ;)

**Comment by michael-ciniawsky** [comment]
Sry that's the responsibility of one of the core members, I will try to ping one in slack, tbh I thought it's up already with a release tagged ¯\_(ツ)_/¯

**Comment by michael-ciniawsky** [comment]
cc @jtangelder @akiran
