### ISSUE TITLE
Module build failed: color: #4a4ae5d1;

### ISSUE THREAD

**Issue by wzup** [webpack-contrib/sass-loader#503]
What's wrong with this CSS rule?
It works just fine in a browser but throws in Webpack `sass-loader`:

```
&:after {
    content: "\f08e";
    font-family: FontAwesome;
    position: absolute;
    font-size: 9px;
    margin-left: 3px;
    color: #4a4ae5d1;  // <== What's wrong with it? `node-sass` throws
}
```

Error:

```
ERROR in ./src/sass/Index.local.scss
    Module build failed: ModuleBuildError: Module build failed:
                                        color: #4a4ae5d1;
                                              ^
          Invalid CSS after "...         color:": expected expression (e.g. 1px, bold), was "#4a4ae5d1;"
          in C:\Users\user\app\src\sass\Index.local.scss (line 651, column 44)
        at runLoaders (C:\Users\user\app\node_modules\webpack\lib\NormalModule.js:195:19)
        at C:\Users\user\app\node_modules\loader-runner\lib\LoaderRunner.js:364:11
        at C:\Users\user\app\node_modules\loader-runner\lib\LoaderRunner.js:230:18
        at context.callback (C:\Users\user\app\node_modules\loader-runner\lib\LoaderRunner.js:111:13)
        at Object.asyncSassJobQueue.push [as callback] (C:\Users\user\app\node_modules\sass-loader\lib\loader.js:55:13)
        at Object.<anonymous> (C:\Users\user\app\node_modules\async\dist\async.js:2244:31)
        at Object.callback (C:\Users\user\app\node_modules\async\dist\async.js:906:16)
        at options.error (C:\Users\user\app\node_modules\node-sass\lib\index.js:294:32)
     @ ./src/js/DashboardTest.js 19:10-37
     @ ./src/js/routes.js
     @ ./src/js/browser.js
```

**Comment by evilebottnawi** [comment]
@wzup seems node-sass doesn't support long color, need investigation, thank for issue

**Comment by evilebottnawi** [comment]
@wzup `libsass` version `3.5.0.beta.2` don't support #rrggbbaa hex color notation, you can try this in https://www.sassmeister.com/. Please create issue in `libsass` about this, Thank you!
