### ISSUE TITLE
scss error: You may need an appropriate loader to handle this file type

### ISSUE THREAD

**Issue by wadewadewadewadewadewade** [webpack-contrib/sass-loader#518]
Hello,

I've been trying for a couple of days to get webpack to build my JS & CSS files. The JS seem to build (tho I still have bugs), but the SCSS keeps throwing a parser error and ending.

> ERROR in ./styles/inline.scss
> Module build failed: ModuleParseError: Module parse failed: Unexpected character '@' (1:0)
> You may need an appropriate loader to handle this file type.
> | @charset "UTF-8";
> | /* global styles */
> | * {
>     at doBuild (E:\Projects\ineffectua-pwa\node_modules\webpack\lib\NormalModule.js:303:19)
>     at runLoaders (E:\Projects\ineffectua-pwa\node_modules\webpack\lib\NormalModule.js:209:11)
>     at E:\Projects\ineffectua-pwa\node_modules\loader-runner\lib\LoaderRunner.js:370:3
>     at iterateNormalLoaders (E:\Projects\ineffectua-pwa\node_modules\loader-runner\lib\LoaderRunner.js:211:10)
>     at iterateNormalLoaders (E:\Projects\ineffectua-pwa\node_modules\loader-runner\lib\LoaderRunner.js:218:10)
>     at E:\Projects\ineffectua-pwa\node_modules\loader-runner\lib\LoaderRunner.js:233:3
>     at context.callback (E:\Projects\ineffectua-pwa\node_modules\loader-runner\lib\LoaderRunner.js:111:13)
>     at E:\Projects\ineffectua-pwa\node_modules\extract-loader\lib\extractLoader.js:101:16
>     at <anonymous>

My repo is here if you're up for helping me. You could be able to just clone it, run `npm install`, and then `npm run build`

https://github.com/wadewadewadewadewadewade/ineffectua-pwa

Thank you for the help! Sorry if this isn't the right place to ask this...I've never written a webpack config file before.

**Comment by wadewadewadewadewadewade** [comment]
I figured it out, by chance.

I replaced my rule for css/scss with below, replacing extract-loader and css-loader with raw-loader

```
      {
        test: /\.(css|sass|scss)$/,
        use: ExtractTextPlugin.extract({
          use: ['raw-loader', 'sass-loader'],
        })
      }
```

**Comment by wadewadewadewadewadewade** [comment]
Whoops, I was wrong. raw-loader stopped the build from crashing, but the scss wasn't being parsed into css...

**Comment by wadewadewadewadewadewade** [comment]
OK, now I got it working- yay! Had to use the pipe/exclamation mark approach I guess.

```{
        test: /\.(css|sass|scss)$/,
        use: ExtractTextPlugin.extract({ fallback: 'style-loader', use: 'css-loader!sass-loader' })
      }```
