### ISSUE TITLE
sass-loader can not work in webpack 4.0.1

### ISSUE THREAD

**Issue by lengjh** [webpack-contrib/sass-loader#540]
**package.json**
```
{
  "name": "webpack4x",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "watch": "webpack --watch",
    "start": "webpack-dev-server --config webpack.dev.js --mode development",
    "build": "webpack --config webpack.prod.js --mode production",
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "author": "",
  "license": "ISC",
  "devDependencies": {
    "clean-webpack-plugin": "^0.1.18",
    "css-loader": "^0.28.10",
    "file-loader": "^1.1.10",
    "html-webpack-plugin": "github:webpack-contrib/html-webpack-plugin",
    "node-sass": "^4.7.2",
    "sass-loader": "^6.0.6",
    "style-loader": "^0.20.2",
    "uglifyjs-webpack-plugin": "^1.2.2",
    "webpack": "^4.0.1",
    "webpack-cli": "^2.0.9",
    "webpack-dev-server": "^3.0.0",
    "webpack-merge": "^4.1.2"
  },
  "dependencies": {
    "lodash": "^4.17.5"
  }
}

```

### `Error Logs`

```
ERROR in ./node_modules/css-loader!./node_modules/sass-loader/lib/loader.js!./src/common.scss
Module build failed: Error: ENOENT: no such file
or directory, scandir 'E:\study\webpack4x\node_modules\node-sass\vendor'
    at Object.fs.readdirSync (fs.js:904:18)
    at Object.getInstalledBinaries (E:\study\webpack4x\node_modules\node-sass\lib\extensions.js:128:13)
    at foundBinariesList (E:\study\webpack4x\node_modules\node-sass\lib\errors.js:20:15)
    at foundBinaries (E:\study\webpack4x\node_modules\node-sass\lib\errors.js:15:5)
    at Object.module.exports.missingBinary (E:\study\webpack4x\node_modules\node-sass\lib\errors.js:45:5)
    at module.exports (E:\study\webpack4x\node_modules\node-sass\lib\binding.js:15:30)
    at Object.<anonymous> (E:\study\webpack4x\node_modules\node-sass\lib\index.js:14:35)
    at Module._compile (E:\study\webpack4x\node_modules\v8-compile-cache\v8-compile-cache.js:178:30)
    at Object.Module._extensions..js (module.js:654:10)
    at Module.load (module.js:556:32)
    at tryModuleLoad (module.js:499:12)
    at Function.Module._load (module.js:491:3)
    at Module.require (module.js:587:17)
    at require (E:\study\webpack4x\node_modules\v8-compile-cache\v8-compile-cache.js:159:20)
    at Object.<anonymous> (E:\study\webpack4x\node_modules\sass-loader\lib\loader.js:3:14)
    at Module._compile (E:\study\webpack4x\node_modules\v8-compile-cache\v8-compile-cache.js:178:30)
    at Object.Module._extensions..js (module.js:654:10)
    at Module.load (module.js:556:32)
    at tryModuleLoad (module.js:499:12)
    at Function.Module._load (module.js:491:3)
    at Module.require (module.js:587:17)
    at require (E:\study\webpack4x\node_modules\v8-compile-cache\v8-compile-cache.js:159:20)
    at loadLoader (E:\study\webpack4x\node_modules\loader-runner\lib\loadLoader.js:13:17)
    at iteratePitchingLoaders (E:\study\webpack4x\node_modules\loader-runner\lib\LoaderRunner.js:169:2)
    at iteratePitchingLoaders (E:\study\webpack4x\node_modules\loader-runner\lib\LoaderRunner.js:165:10)
    at E:\study\webpack4x\node_modules\loader-runner\lib\LoaderRunner.js:173:18
    at loadLoader (E:\study\webpack4x\node_modules\loader-runner\lib\loadLoader.js:36:3)
    at iteratePitchingLoaders (E:\study\webpack4x\node_modules\loader-runner\lib\LoaderRunner.js:169:2)
    at runLoaders (E:\study\webpack4x\node_modules\loader-runner\lib\LoaderRunner.js:362:2)
    at NormalModule.doBuild (E:\study\webpack4x\node_modules\webpack\lib\NormalModule.js:219:3)
    at NormalModule.build (E:\study\webpack4x\node_modules\webpack\lib\NormalModule.js:337:15)
    at Compilation.buildModule (E:\study\webpack4x\node_modules\webpack\lib\Compilation.js:346:10)
    at factory.create (E:\study\webpack4x\node_modules\webpack\lib\Compilation.js:572:15)
    at factory (E:\study\webpack4x\node_modules\webpack\lib\NormalModuleFactory.js:366:6)
    at hooks.afterResolve.callAsync (E:\study\webpack4x\node_modules\webpack\lib\NormalModuleFactory.js:143:13)
    at AsyncSeriesWaterfallHook.eval [as callAsync] (eval at create (E:\study\webpack4x\node_modules\tapable\lib\HookCodeFactory.js:24:12), <anonymous>:6:1)
 @ ./src/common.scss 2:14-118
 @ ./src/index.js
```

**Comment by evilebottnawi** [comment]
@lengjh Can you create minimum reproducible test repo, seems bug in `node-sass` :confused:

**Comment by spock123** [comment]
@lengjh  I'm having same issue. Any setup with Webpack 4 + Sass-loader will give this error.

For the record, I also tried with https://github.com/yibn2008/fast-sass-loader  with the same result so your suspision on node-sass seems to be correct.

**Comment by evilebottnawi** [comment]
We migrate on webpack@4 and also use `sass-loader` and all works fine :confused: can you create minimum reproducible test repo? Or put here stack trace?

**Comment by evilebottnawi** [comment]
@spock123 Also you use mac/linux/windows?

**Comment by spock123** [comment]
@evilebottnawi  this is a surprise to me.. I'll have to investigate tonight :)

I use Linux/Ubuntu, Node 8.9.4, Typescript 2.6.2

```
ERROR in ./node_modules/css-loader!./node_modules/fast-sass-loader/lib!./src/styles/index.scss
Module build failed: TypeError: Cannot read property 'context' of undefined
    at getLoaderConfig (/home/lrj/project/2017.OSB/frontend/node_modules/fast-sass-loader/lib/index.js:72:29)
    at Object.module.exports (/home/lrj/project/2017.OSB/frontend/node_modules/fast-sass-loader/lib/index.js:224:17)
 @ ./src/styles/index.scss 2:14-127
 @ ./src/app/vendors.ts
 @ multi (webpack)-dev-server/client?http://0.0.0.0:9000 ./src/app/vendors.ts
```

**Comment by evilebottnawi** [comment]
@spock123 very strange we don't use `context` anywhere. Maybe you can provide test repo?

**Comment by spock123** [comment]
@evilebottnawi  I know webpack4 changed  this.context => this.rootContext, could this be the issue?

**Comment by spock123** [comment]
@evilebottnawi  Please disregard, I have just tested more and I don't think the issue is with sass-loader or node-sass. The error I have is because of importing woff2 font files (inside sass files).

Likely the issue is with other loaders (like file-loader).. 

I'm sorry.. I'll investigate more but most likely sass-loader works beautifully :)

**Comment by evilebottnawi** [comment]
@spock123 anyway when you find problem please describe her here :+1:

**Comment by michael-ciniawsky** [comment]
```
ERROR in ./node_modules/css-loader!./node_modules/=> fast-sass-loader <= /lib!./src/styles/index.scss
```

`fast-sass-loader !== sass-loader`, please open an issue in `fast-sass-loader` instead

**Comment by spock123** [comment]
@evilebottnawi  The issue was with awesome-typescript-loader.

Using ts-loader instead solved the issue. Hope this helps others with similar issue.

**Comment by spock123** [comment]
@michael-ciniawsky 

I think you missed this quote: 

> With fast-sass-loader (same error message with sass-loader)

**Comment by MortimerJarasemy** [comment]
Hello I am attempting to have the following an index file with  other scss imported under to follow an order for my components, I am using webpack 4 and guetting an error for using "imports"

--Index
  --header
  --about
  --etc

^
      Invalid CSS after "": expected 1 selector or at-rule, was "*/"
      in /Users/laxosceles/react-portfolio-solstice/src/artistry/sass/app.scss (line 1, column 1)
 @ ./src/artistry/sass/index.scss 2:14-129 21:1-42:3 21:127-42:2 22:19-134
 @ ./src/index.js
 @ multi (webpack)-dev-server/client?http://localhost:8084 webpack/hot/dev-server ./src

thats what I am guetting for using imports

**Comment by befika** [comment]
here is mi ionic info
Ionic:

   ionic (Ionic CLI)             : 4.10.3 (C:\Users\befika\AppData\Roaming\npm\node_modules\ionic)
   Ionic Framework               : @ionic/angular 4.0.2
   @angular-devkit/build-angular : 0.12.4
   @angular-devkit/schematics    : 7.2.4
   @angular/cli                  : 7.3.2
   @ionic/angular-toolkit        : 1.4.0

Cordova:

   cordova (Cordova CLI) : 8.1.2 (cordova-lib@8.1.1)
   Cordova Platforms     : android 7.1.4
   Cordova Plugins       : cordova-plugin-ionic-webview 3.1.2, (and 4 other plugins)

System:

   NodeJS : v11.10.0 (C:\Program Files\nodejs\node.exe)
   npm    : 6.8.0
   OS     : Windows 10
