### ISSUE TITLE
import css: Module not found: Error: Can't resolve

### ISSUE THREAD

**Issue by willin** [webpack-contrib/sass-loader#584]
Webpack config:

```js
module.exports = [
  {
    entry: './src/style/style.scss',
    output: {
      // This is necessary for webpack to compile
      // But we never use style-bundle.js
      filename: 'style-bundle.js'
    },
    module: {
      rules: [{
        test: /\.scss$/,
        use: [
          {
            loader: 'file-loader',
            options: {
              name: 'bundle.css'
            }
          },
          'extract-loader',
          'css-loader',
          'postcss-loader',
          {
            loader: 'sass-loader',
            options: {
              includePaths: ['./node_modules']
            }
          }
        ]
      }]
    }
  },
  {
    entry: './src/app.js',
    output: {
      filename: 'bundle.js'
    },
    module: {
      rules: [{
        test: /\.js$/,
        use: 'babel-loader'
      }]
    }
  }
];
```

scss:

```scss
@import "@material/button/mdc-button";
@import "@material/select/mdc-select";
@import "@material/textfield/mdc-text-field";
// error here
@import 'leaflet/dist/leaflet.css';
```

err info:

```
ERROR in ./src/style/style.scss
    Module build failed (from ./node_modules/extract-loader/lib/extractLoader.js):
    ModuleNotFoundError: Module not found: Error: Can't resolve './leaflet/dist/leaflet.css' in '/Users/willin/Documents/dwing/fe/uss-fe/src/style'
        at factory.create (/Users/willin/Documents/dwing/fe/uss-fe/node_modules/webpack/lib/Compilation.js:547:10)
        at factory (/Users/willin/Documents/dwing/fe/uss-fe/node_modules/webpack/lib/NormalModuleFactory.js:397:22)
        at resolver (/Users/willin/Documents/dwing/fe/uss-fe/node_modules/webpack/lib/NormalModuleFactory.js:130:21)
        at asyncLib.parallel (/Users/willin/Documents/dwing/fe/uss-fe/node_modules/webpack/lib/NormalModuleFactory.js:224:22)
        at /Users/willin/Documents/dwing/fe/uss-fe/node_modules/neo-async/async.js:2817:7
        at /Users/willin/Documents/dwing/fe/uss-fe/node_modules/neo-async/async.js:6783:13
        at normalResolver.resolve (/Users/willin/Documents/dwing/fe/uss-fe/node_modules/webpack/lib/NormalModuleFactory.js:214:25)
        at doResolve (/Users/willin/Documents/dwing/fe/uss-fe/node_modules/enhanced-resolve/lib/Resolver.js:184:12)
        at hook.callAsync (/Users/willin/Documents/dwing/fe/uss-fe/node_modules/enhanced-resolve/lib/Resolver.js:238:5)
        at _fn0 (eval at create (/Users/willin/Documents/dwing/fe/uss-fe/node_modules/tapable/lib/HookCodeFactory.js:24:12), <anonymous>:15:1)
     @ multi (webpack)-dev-server/client?http://localhost:8080 ./src/style/style.scss

    ERROR in ./src/style/style.scss
    Module not found: Error: Can't resolve './leaflet/dist/leaflet.css' in '/Users/willin/Documents/dwing/fe/uss-fe/src/style'
     @ ./src/style/style.scss
     @ multi (webpack)-dev-server/client?http://localhost:8080 ./src/style/style.scss
```

**Comment by evilebottnawi** [comment]
@willin because you don't have file or have invalid path to file

**Comment by willin** [comment]
https://github.com/wshow/sass-demo

**Comment by evilebottnawi** [comment]
@willin use `@import '~leaflet/dist/leaflet.css';`
https://github.com/webpack-contrib/sass-loader#imports

**Comment by stevenvachon** [comment]
@evilebottnawi why should we have to rewrite our deeper SCSS files when switching to webpack? For example, if `entry.scss` imports `~alias/deep.scss` which imports `relative/deeper.scss`, the relative path should still work.
