### ISSUE TITLE
module build failed

### ISSUE THREAD

**Issue by Ameeno0** [webpack-contrib/sass-loader#621]
ERROR in ./src/app/calender/calender.component.scss
Module build failed (from ./node_modules/sass-loader/lib/loader.js):
Error: Cannot find module 'node-sass'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:587:15)
    at Function.Module._load (internal/modules/cjs/loader.js:513:25)
    at Module.require (internal/modules/cjs/loader.js:643:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.sassLoader (C:\Users\nooru\tmt-hr\tmt-hr-dashboard\node_modules\sass-loader\lib\loader.js:46:72)

**Comment by Ameeno0** [comment]
i tried did not work, so i changed the scss file to css file, now its working fine
