### ISSUE TITLE
Module build failed undefined join

### ISSUE THREAD

**Issue by vaheedxp** [webpack-contrib/sass-loader#654]
` ERROR  Failed to compile with 2 errors                                                                                                                       8:49:23 PM

 error  in ./resources/sass/app.scss

Module build failed (from ./node_modules/css-loader/index.js):
ModuleBuildError: Module build failed (from ./node_modules/sass-loader/lib/loader.js):

undefined
       ^
      Join(null, "variables"): part 0 was null, but part 1 was not.
@import 'variables';
        ^^^^^^^^^^^
  stdin 2:9  root stylesheet
      in C:\Users\TAQI VAHEED\Desktop\#Coding\resPro\resources\sass\app.scss (line 2, column 9)
    at runLoaders (C:\Users\TAQI VAHEED\Desktop\#Coding\resPro\node_modules\webpack\lib\NormalModule.js:301:20)
    at C:\Users\TAQI VAHEED\Desktop\#Coding\resPro\node_modules\loader-runner\lib\LoaderRunner.js:364:11
    at C:\Users\TAQI VAHEED\Desktop\#Coding\resPro\node_modules\loader-runner\lib\LoaderRunner.js:230:18
    at context.callback (C:\Users\TAQI VAHEED\Desktop\#Coding\resPro\node_modules\loader-runner\lib\LoaderRunner.js:111:13)
    at render (C:\Users\TAQI VAHEED\Desktop\#Coding\resPro\node_modules\sass-loader\lib\loader.js:52:13)
    at Function.$2 (C:\Users\TAQI VAHEED\Desktop\#Coding\resPro\node_modules\sass\sass.dart.js:25378:48)
    at vB.$2 (C:\Users\TAQI VAHEED\Desktop\#Coding\resPro\node_modules\sass\sass.dart.js:16223:16)
    at tz.ve (C:\Users\TAQI VAHEED\Desktop\#Coding\resPro\node_modules\sass\sass.dart.js:9275:42)
    at tz.vd (C:\Users\TAQI VAHEED\Desktop\#Coding\resPro\node_modules\sass\sass.dart.js:9277:32)
    at ic.uo (C:\Users\TAQI VAHEED\Desktop\#Coding\resPro\node_modules\sass\sass.dart.js:8583:46)
    at t6.$0 (C:\Users\TAQI VAHEED\Desktop\#Coding\resPro\node_modules\sass\sass.dart.js:8728:7)
    at Object.eu (C:\Users\TAQI VAHEED\Desktop\#Coding\resPro\node_modules\sass\sass.dart.js:1569:80)
    at aj.bd (C:\Users\TAQI VAHEED\Desktop\#Coding\resPro\node_modules\sass\sass.dart.js:8646:3)
    at is.bd (C:\Users\TAQI VAHEED\Desktop\#Coding\resPro\node_modules\sass\sass.dart.js:8576:25)
    at is.cF (C:\Users\TAQI VAHEED\Desktop\#Coding\resPro\node_modules\sass\sass.dart.js:8563:6)
    at oy.cF (C:\Users\TAQI VAHEED\Desktop\#Coding\resPro\node_modules\sass\sass.dart.js:8350:35)
    at Object.o (C:\Users\TAQI VAHEED\Desktop\#Coding\resPro\node_modules\sass\sass.dart.js:1442:19)
    at C:\Users\TAQI VAHEED\Desktop\#Coding\resPro\node_modules\sass\sass.dart.js:5284:51
    at w0.a (C:\Users\TAQI VAHEED\Desktop\#Coding\resPro\node_modules\sass\sass.dart.js:1453:71)
    at w0.$2 (C:\Users\TAQI VAHEED\Desktop\#Coding\resPro\node_modules\sass\sass.dart.js:8365:23)
    at uC.$2 (C:\Users\TAQI VAHEED\Desktop\#Coding\resPro\node_modules\sass\sass.dart.js:8360:25)
    at tz.ve (C:\Users\TAQI VAHEED\Desktop\#Coding\resPro\node_modules\sass\sass.dart.js:9275:42)
    at tz.vd (C:\Users\TAQI VAHEED\Desktop\#Coding\resPro\node_modules\sass\sass.dart.js:9277:32)
    at ic.uo (C:\Users\TAQI VAHEED\Desktop\#Coding\resPro\node_modules\sass\sass.dart.js:8583:46)
    at t6.$0 (C:\Users\TAQI VAHEED\Desktop\#Coding\resPro\node_modules\sass\sass.dart.js:8728:7)
    at Object.eu (C:\Users\TAQI VAHEED\Desktop\#Coding\resPro\node_modules\sass\sass.dart.js:1569:80)
    at aj.bd (C:\Users\TAQI VAHEED\Desktop\#Coding\resPro\node_modules\sass\sass.dart.js:8646:3)
    at is.bd (C:\Users\TAQI VAHEED\Desktop\#Coding\resPro\node_modules\sass\sass.dart.js:8576:25)
    at is.cF (C:\Users\TAQI VAHEED\Desktop\#Coding\resPro\node_modules\sass\sass.dart.js:8563:6)
    at oy.cF (C:\Users\TAQI VAHEED\Desktop\#Coding\resPro\node_modules\sass\sass.dart.js:8350:35)
    at Object.o (C:\Users\TAQI VAHEED\Desktop\#Coding\resPro\node_modules\sass\sass.dart.js:1442:19)
    at C:\Users\TAQI VAHEED\Desktop\#Coding\resPro\node_modules\sass\sass.dart.js:5835:52
    at w0.a (C:\Users\TAQI VAHEED\Desktop\#Coding\resPro\node_modules\sass\sass.dart.js:1453:71)
    at w0.$2 (C:\Users\TAQI VAHEED\Desktop\#Coding\resPro\node_modules\sass\sass.dart.js:8365:23)
    at uC.$2 (C:\Users\TAQI VAHEED\Desktop\#Coding\resPro\node_modules\sass\sass.dart.js:8360:25)
    at tz.ve (C:\Users\TAQI VAHEED\Desktop\#Coding\resPro\node_modules\sass\sass.dart.js:9275:42)

 error  in ./resources/sass/app.scss

Module build failed (from ./node_modules/sass-loader/lib/loader.js):
Unsupported operation: Cannot extract a file path from a URI with a fragment component

 @ ./resources/sass/app.scss 2:14-254

     Asset      Size   Chunks             Chunk Names
/js/app.js  2.46 MiB  /js/app  [emitted]  /js/app

ERROR in ./resources/sass/app.scss
Module build failed (from ./node_modules/css-loader/index.js):
ModuleBuildError: Module build failed (from ./node_modules/sass-loader/lib/loader.js):

undefined
       ^
      Join(null, "variables"): part 0 was null, but part 1 was not.
@import 'variables';
        ^^^^^^^^^^^
  stdin 2:9  root stylesheet
      in C:\Users\TAQI VAHEED\Desktop\#Coding\resPro\resources\sass\app.scss (line 2, column 9)
    at runLoaders (C:\Users\TAQI VAHEED\Desktop\#Coding\resPro\node_modules\webpack\lib\NormalModule.js:301:20)
    at C:\Users\TAQI VAHEED\Desktop\#Coding\resPro\node_modules\loader-runner\lib\LoaderRunner.js:364:11
    at C:\Users\TAQI VAHEED\Desktop\#Coding\resPro\node_modules\loader-runner\lib\LoaderRunner.js:230:18
    at context.callback (C:\Users\TAQI VAHEED\Desktop\#Coding\resPro\node_modules\loader-runner\lib\LoaderRunner.js:111:13)
    at render (C:\Users\TAQI VAHEED\Desktop\#Coding\resPro\node_modules\sass-loader\lib\loader.js:52:13)
    at Function.$2 (C:\Users\TAQI VAHEED\Desktop\#Coding\resPro\node_modules\sass\sass.dart.js:25378:48)
    at vB.$2 (C:\Users\TAQI VAHEED\Desktop\#Coding\resPro\node_modules\sass\sass.dart.js:16223:16)
    at tz.ve (C:\Users\TAQI VAHEED\Desktop\#Coding\resPro\node_modules\sass\sass.dart.js:9275:42)
    at tz.vd (C:\Users\TAQI VAHEED\Desktop\#Coding\resPro\node_modules\sass\sass.dart.js:9277:32)
    at ic.uo (C:\Users\TAQI VAHEED\Desktop\#Coding\resPro\node_modules\sass\sass.dart.js:8583:46)
    at t6.$0 (C:\Users\TAQI VAHEED\Desktop\#Coding\resPro\node_modules\sass\sass.dart.js:8728:7)
    at Object.eu (C:\Users\TAQI VAHEED\Desktop\#Coding\resPro\node_modules\sass\sass.dart.js:1569:80)
    at aj.bd (C:\Users\TAQI VAHEED\Desktop\#Coding\resPro\node_modules\sass\sass.dart.js:8646:3)
    at is.bd (C:\Users\TAQI VAHEED\Desktop\#Coding\resPro\node_modules\sass\sass.dart.js:8576:25)
    at is.cF (C:\Users\TAQI VAHEED\Desktop\#Coding\resPro\node_modules\sass\sass.dart.js:8563:6)
    at oy.cF (C:\Users\TAQI VAHEED\Desktop\#Coding\resPro\node_modules\sass\sass.dart.js:8350:35)
    at Object.o (C:\Users\TAQI VAHEED\Desktop\#Coding\resPro\node_modules\sass\sass.dart.js:1442:19)
    at C:\Users\TAQI VAHEED\Desktop\#Coding\resPro\node_modules\sass\sass.dart.js:5284:51
    at w0.a (C:\Users\TAQI VAHEED\Desktop\#Coding\resPro\node_modules\sass\sass.dart.js:1453:71)
    at w0.$2 (C:\Users\TAQI VAHEED\Desktop\#Coding\resPro\node_modules\sass\sass.dart.js:8365:23)
    at uC.$2 (C:\Users\TAQI VAHEED\Desktop\#Coding\resPro\node_modules\sass\sass.dart.js:8360:25)
    at tz.ve (C:\Users\TAQI VAHEED\Desktop\#Coding\resPro\node_modules\sass\sass.dart.js:9275:42)
    at tz.vd (C:\Users\TAQI VAHEED\Desktop\#Coding\resPro\node_modules\sass\sass.dart.js:9277:32)
    at ic.uo (C:\Users\TAQI VAHEED\Desktop\#Coding\resPro\node_modules\sass\sass.dart.js:8583:46)
    at t6.$0 (C:\Users\TAQI VAHEED\Desktop\#Coding\resPro\node_modules\sass\sass.dart.js:8728:7)
    at Object.eu (C:\Users\TAQI VAHEED\Desktop\#Coding\resPro\node_modules\sass\sass.dart.js:1569:80)
    at aj.bd (C:\Users\TAQI VAHEED\Desktop\#Coding\resPro\node_modules\sass\sass.dart.js:8646:3)
    at is.bd (C:\Users\TAQI VAHEED\Desktop\#Coding\resPro\node_modules\sass\sass.dart.js:8576:25)
    at is.cF (C:\Users\TAQI VAHEED\Desktop\#Coding\resPro\node_modules\sass\sass.dart.js:8563:6)
    at oy.cF (C:\Users\TAQI VAHEED\Desktop\#Coding\resPro\node_modules\sass\sass.dart.js:8350:35)
    at Object.o (C:\Users\TAQI VAHEED\Desktop\#Coding\resPro\node_modules\sass\sass.dart.js:1442:19)
    at C:\Users\TAQI VAHEED\Desktop\#Coding\resPro\node_modules\sass\sass.dart.js:5835:52
    at w0.a (C:\Users\TAQI VAHEED\Desktop\#Coding\resPro\node_modules\sass\sass.dart.js:1453:71)
    at w0.$2 (C:\Users\TAQI VAHEED\Desktop\#Coding\resPro\node_modules\sass\sass.dart.js:8365:23)
    at uC.$2 (C:\Users\TAQI VAHEED\Desktop\#Coding\resPro\node_modules\sass\sass.dart.js:8360:25)
    at tz.ve (C:\Users\TAQI VAHEED\Desktop\#Coding\resPro\node_modules\sass\sass.dart.js:9275:42)
 @ ./resources/sass/app.scss

ERROR in ./resources/sass/app.scss (./node_modules/css-loader??ref--5-2!./node_modules/postcss-loader/src??postcss!./node_modules/resolve-url-loader??ref--5-4!./node_modules/sass-loader/lib/loader.js??ref--5-5!./resources/sass/app.scss)
Module build failed (from ./node_modules/sass-loader/lib/loader.js):
Unsupported operation: Cannot extract a file path from a URI with a fragment component
 @ ./resources/sass/app.scss 2:14-254
`

**Comment by evilebottnawi** [comment]
It looks like you just deleted our lovely crafted issue template. It was there for good reasons. Please help us solving your issue by answering the questions asked in this template. I'm closing this. Please either update the issue with the template and reopen, or open a new issue.
