### ISSUE TITLE
does not resolve the implementation from devDependencies

### ISSUE THREAD

**Issue by isum** [webpack-contrib/sass-loader#672]
* Operating System: Linux
* Node Version: v11.11.0
* NPM Version: 6.9.0
* webpack Version: 4.29.6
* sass-loader Version: 7.1.0

### Expected Behavior

As said in documentation:

> By default the loader resolve the implementation based on your dependencies. Just add required implementation to package.json (node-sass or sass package) and install dependencies.

### Actual Behavior

But it does not resolve, unless `implementation: require('sass')` option specified manually.

Console error:
```
    ERROR in ./src/index.css (./node_modules/css-loader/dist/cjs.js??ref--5-1!./node_modules/sass-loader/lib/loader.js??ref--5-2!./src/index.css)
    Module build failed (from ./node_modules/sass-loader/lib/loader.js):
    Error: Cannot find module 'node-sass'
        at Function.Module._resolveFilename (internal/modules/cjs/loader.js:649:15)
        at Function.Module._load (internal/modules/cjs/loader.js:575:25)
        at Module.require (internal/modules/cjs/loader.js:705:19)
        at require (/home/isu/project/baron/chat-widget/node_modules/v8-compile-cache/v8-compile-cache.js:159:20)
        at Object.sassLoader (/home/isu/project/baron/chat-widget/node_modules/sass-loader/lib/loader.js:46:72)
```

### Code

```js
// webpack.config.js
const HtmlWebpackPlugin = require('html-webpack-plugin');
const MiniCssExtractPlugin = require('mini-css-extract-plugin');
const CleanWebpackPlugin = require('clean-webpack-plugin');
module.exports = {
  entry: './src/index.js',
  module: {
    rules: [
      {test: /\.js$/, exclude: /node_modules/, use: 'babel-loader'},
      {test: /\.(sa|sc|c)ss$/, use: [
        MiniCssExtractPlugin.loader,
        {loader: 'css-loader', options: {modules: true}},
        {loader: 'sass-loader', options: {/*implementation: require('sass')*/}},
      ]},
      {test: /\.(png|svg|jpg|gif)$/, use: 'file-loader'},
      {test: /\.(woff|woff2|eot|ttf|otf)$/, use: 'file-loader'},
    ]
  },
  plugins: [
    new HtmlWebpackPlugin({template: 'src/index.html'}),
    new MiniCssExtractPlugin({}),
    new CleanWebpackPlugin(),
  ],
  output: {
    library: 'MyChatWidget',
    libraryTarget: 'umd',
    libraryExport: 'default',
    path: path.resolve(__dirname, 'build')
  },
};
```
### How Do We Reproduce?

```js
// package.json
{
  "scripts": {
    "build": "webpack --config webpack.production.js"
  },
  "devDependencies": {
    "@babel/core": "^7.4.0",
    "@babel/plugin-transform-react-jsx": "^7.3.0",
    "@babel/preset-env": "^7.4.2",
    "babel-loader": "^8.0.5",
    "clean-webpack-plugin": "^2.0.1",
    "css-loader": "^2.1.1",
    "file-loader": "^3.0.1",
    "html-webpack-plugin": "^3.2.0",
    "mini-css-extract-plugin": "^0.5.0",
    "preact": "^8.4.2",
    "sass": "^1.17.3",
    "sass-loader": "^7.1.0",
    "webpack": "^4.29.6",
    "webpack-bundle-analyzer": "^3.1.0",
    "webpack-cli": "^3.3.0",
    "webpack-dev-server": "^3.2.1",
    "webpack-merge": "^4.2.1"
  }
}
```

**Comment by evilebottnawi** [comment]
Yep, auto resolving `sass` (`dart`) is not published yet (it is only in master), anyway we done this in near future (many other issues right now)

**Comment by evilebottnawi** [comment]
You need use `implementation` option for this right now
