### ISSUE TITLE
Module build failed: TypeError: this.getResolve is not a function

### ISSUE THREAD

**Issue by VirtualAirwaves** [webpack-contrib/sass-loader#761]
- Operating System: centos 7
- Node Version: 6.17.1
- NPM Version: 3.10.10
- webpack Version: 4.4.0
- sass-loader Version: 8.0.0

### Expected Behavior

I expected my SASS to compile

### Actual Behavior

```
Module build failed: ModuleBuildError: Module build failed: TypeError: this.getResolve is not a function
    at Object.loader (/home/famserve/cb/va_web/assets/node_modules/sass-loader/dist/index.js:52:26)
    at runLoaders (/home/famserve/cb/va_web/assets/node_modules/webpack/lib/NormalModule.js:244:20)
    at /home/famserve/cb/va_web/assets/node_modules/loader-runner/lib/LoaderRunner.js:367:11
    at /home/famserve/cb/va_web/assets/node_modules/loader-runner/lib/LoaderRunner.js:233:18
    at runSyncOrAsync (/home/famserve/cb/va_web/assets/node_modules/loader-runner/lib/LoaderRunner.js:143:3)
    at iterateNormalLoaders (/home/famserve/cb/va_web/assets/node_modules/loader-runner/lib/LoaderRunner.js:232:2)          at Array.<anonymous> (/home/famserve/cb/va_web/assets/node_modules/loader-runner/lib/LoaderRunner.js:205:4)
    at Storage.finished (/home/famserve/cb/va_web/assets/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:43:1
```

```js
// webpack.config.js

`const path = require('path');                                                                                           const glob = require('glob');                                                                                           const MiniCssExtractPlugin = require('mini-css-extract-plugin');                                                        const UglifyJsPlugin = require('uglifyjs-webpack-plugin');                                                              const OptimizeCSSAssetsPlugin = require('optimize-css-assets-webpack-plugin');                                          const CopyWebpackPlugin = require('copy-webpack-plugin');                                                                                                                                                                                       module.exports = (env, options) => ({                                                                                     optimization: {                                                                                                           minimizer: [                                                                                                              new UglifyJsPlugin({ cache: true, parallel: true, sourceMap: false }),                                                  new OptimizeCSSAssetsPlugin({})                                                                                       ]                                                                                                                     },                                                                                                                      entry: {                                                                                                                    './js/app.js': ['./js/app.js'].concat(glob.sync('./vendor/**/*.js'))                                                },                                                                                                                      output: {                                                                                                                 filename: 'app.js',                                                                                                     path: path.resolve(__dirname, '../priv/static/js')                                                                    },                                                                                                                      module: {                                                                                                                 rules: [                                                                                                                  {                                                                                                                         test: /\.js$/,                                                                                                          exclude: /node_modules/,                                                                                                use: {                                                                                                                    loader: 'babel-loader'                                                                                                }                                                                                                                     },                                                                                                                      {                                                                                                                         test: /\.css$/,                                                                                                         use: [MiniCssExtractPlugin.loader, 'css-loader']                                                                      },                                                                                                                      {                                                                                                                         test: /\.elm$/,                                                                                                         exclude: [/elm-stuff/, /node_modules/],                                                                                 use: {                                                                                                                    loader: 'elm-webpack-loader',                                                                                           options: {                                                                                                                  debug: false                                                                                                        }                                                                                                                     }                                                                                                                     },                                                                                                                      {test: /\.scss$/,                                                                                                         use: [                                                                                                                      MiniCssExtractPlugin.loader,                                                                                            {                                                                                                                         loader: 'css-loader'                                                                                                  },                                                                                                                      {                                                                                                                         loader: 'sass-loader',                                                                                                  options: {                                                                                                                sourceMap: true                                                                                                       }                                                                                                                     }                                                                                                                     ]                                                                                                                   }                                                                                                                     ]                                                                                                                     },                                                                                                                      plugins: [                                                                                                                new MiniCssExtractPlugin({ filename: '../css/app.css' }),                                                               new CopyWebpackPlugin([{ from: 'static/', to: '../' }])                                                               ]                                                                                                                     });     `                                                                                           
```

### How Do We Reproduce?

I have been unable to get this to work at all. There seems to be something fundamentally wrong with these versions, which I presume to be the latest. I can see the call to getResolve inside the source to sass-loader/index.js so I don't know why it wasn't defined

**Comment by VirtualAirwaves** [comment]
Figured it out! I didn't have the latest version of everything. I needed webpack 4.40.2 and it fixed it. (I think 4.36.x or later would work).

**Comment by yogiprsetya** [comment]
I have same problem, how to fix it?

**Comment by hidaytrahman** [comment]
How to update webpack to the latest version?

**Comment by ngryman** [comment]
It's happening to me with `webpack@4.41.2`.

**Comment by ngryman** [comment]
It appears that it has to do something with `thread-loader`.

When I use this loaders chain the error happens:

```js
[
  {
    loader: 'thread-loader',
    options: threadLoaderOptions,
  },
  'css-loader',
  'sass-loader'
]
```

However, if I remove `thread-loader` everything works fine.

**Comment by rbfonbuena** [comment]
Posting this in case a search sent someone here with the same issue. Downgrading from sass-loader 8.0.0 to 7.3.1 fixed it for me on new builds with Webpack 4.4.0.

**Comment by Legends** [comment]
I have this error when I install `webpack v4.6`

**Comment by blackbart420** [comment]
> Posting this in case a search sent someone here with the same issue. Downgrading from sass-loader 8.0.0 to 7.3.1 fixed it for me on new builds with Webpack 4.4.0.

Works for me, thank you so much @rbfonbuena

**Comment by Dhanush623** [comment]
> Posting this in case a search sent someone here with the same issue. Downgrading from sass-loader 8.0.0 to 7.3.1 fixed it for me on new builds with Webpack 4.4.0.

This works for me

**Comment by thefrontend2web** [comment]
> Posting this in case a search sent someone here with the same issue. Downgrading from sass-loader 8.0.0 to 7.3.1 fixed it for me on new builds with Webpack 4.4.0.

Thanks, works for me too

**Comment by sudamonline** [comment]
How can we change or update the webpack verison?

**Comment by rainke** [comment]
style-loader is ok, but MiniCssExtractPlugin.loader has the same error
```
[
  MiniCssExtractPlugin.loader,
   'thread-loader',
   'css-loader', 
  {
    loader: 'sass-loader', 
    options: { implementation: require('sass') }
  }
]
```

**Comment by graciolli-f** [comment]
> Posting this in case a search sent someone here with the same issue. Downgrading from sass-loader 8.0.0 to 7.3.1 fixed it for me on new builds with Webpack 4.4.0.

Thank you so much for this!!!

**Comment by ValentinnDimitroff** [comment]
> 
> 
> Posting this in case a search sent someone here with the same issue. Downgrading from sass-loader 8.0.0 to 7.3.1 fixed it for me on new builds with Webpack 4.4.0.

Still saving lifes! Thank you!

**Comment by Curzey** [comment]
> Posting this in case a search sent someone here with the same issue. Downgrading from sass-loader 8.0.0 to 7.3.1 fixed it for me on new builds with Webpack 4.4.0.

This also works for me. Thank you!

**Comment by rodrigommv1987** [comment]
> Posting this in case a search sent someone here with the same issue. Downgrading from sass-loader 8.0.0 to 7.3.1 fixed it for me on new builds with Webpack 4.4.0.

thanks for this!

**Comment by rubberDuckyyy** [comment]
THIS WORKED FOR ME! 

npm install webpack@4.40.2

**Comment by ChicagoStats** [comment]
> THIS WORKED FOR ME!
> 
> npm install webpack@4.40.2

Amazing!!!! thanks

**Comment by ruvaleev** [comment]
> npm install webpack@4.40.2

Thank you so much!

**Comment by HenrijsS** [comment]
This issue is still present in ^11.0.0
Downgrading sass-loader to 10.1.1 works perfectly fine.

**Comment by saip12** [comment]
Getting below error when Angular version is upgraded. 

Module build failed (from ./node_modules/@angular-devkit/build-angular/node_modules/sass-loader/dist/cjs.js):
SassError: Invalid CSS after "...oc-primary: mat": expected expression (e.g. 1px, bold), was ".define-palette($lo"
        on line 70 of src/theme.scss
        
 Inside cjs.js File
 

 "use strict";

const loader = require('./index');

module.exports = loader.default;

Tried above solutions and nothing worked so far. Any ideas how to fix it? Thanks!
