### ISSUE TITLE
The loader does not resolve the implementation based on dependencies

### ISSUE THREAD

**Issue by ip1981** [webpack-contrib/sass-loader#764]
The README file says:

> By default the loader resolve the implementation based on your dependencies. Just add required implementation to package.json (node-sass or sass package) and install dependencies.

But in fact when I drop `node-sass` and add `sass` I get a failure:

```
Module build failed (from ./node_modules/sass-loader/lib/loader.js):
    Error: Cannot find module 'node-sass'
        at Function.Module._resolveFilename (internal/modules/cjs/loader.js:581:15)
        at Function._module2.default._resolveFilename (.../node_modules/require-hacker/babel-transpiled-modules/require hacker.js:442:34)
        at Function.Module._load (internal/modules/cjs/loader.js:507:25)
        at Module.require (internal/modules/cjs/loader.js:637:17)
...
```

**Comment by evilebottnawi** [comment]
It looks like you just deleted our lovely crafted issue template. It was there for good reasons. Please help us solving your issue by answering the questions asked in this template. I'm closing this. Please either update the issue with the template and reopen, or open a new issue.

You should install `node-sass`
