### ISSUE TITLE
Version: 8.0.0 TypeError: this.getResolve is not a function

### ISSUE THREAD

**Issue by jerryji** [webpack-contrib/sass-loader#778]
- Operating System: Ubuntu 18.04
- Node Version: v12.13.1
- NPM Version: 6.13.1
- webpack Version: 4.4.1
- sass-loader Version: 8.0.0

### Expected Behavior

successful webpack

### Actual Behavior

```
ERROR in ../node_modules/mini-css-extract-plugin/dist/loader.js!../node_modules/css-loader/dist/cjs.js!../node_modules/sass-loader/dist/cjs.js!./app/static/css/index.scss
Module build failed: ModuleBuildError: Module build failed: TypeError: this.getResolve is not a function
    at Object.loader (/home/jerryj/workspace/ethwall/node_modules/sass-loader/dist/index.js:52:26)
    at /usr/lib/node_modules/webpack/lib/NormalModule.js:244:20
    at /usr/lib/node_modules/webpack/node_modules/loader-runner/lib/LoaderRunner.js:364:11
    at /usr/lib/node_modules/webpack/node_modules/loader-runner/lib/LoaderRunner.js:230:18
    at runSyncOrAsync (/usr/lib/node_modules/webpack/node_modules/loader-runner/lib/LoaderRunner.js:143:3)
    at iterateNormalLoaders (/usr/lib/node_modules/webpack/node_modules/loader-runner/lib/LoaderRunner.js:229:2)
    at Array.<anonymous> (/usr/lib/node_modules/webpack/node_modules/loader-runner/lib/LoaderRunner.js:202:4)
    at Storage.finished (/usr/lib/node_modules/webpack/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:43:16)
    at /usr/lib/node_modules/webpack/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:79:9
    at /usr/lib/node_modules/webpack/node_modules/graceful-fs/graceful-fs.js:78:16
    at FSReqCallback.readFileAfterClose [as oncomplete] (internal/fs/read_file_context.js:61:3)
 @ ./app/static/css/index.scss 1:14-200
 @ ./app/static/js/main.js
 @ multi babel-polyfill ./app/static/js/main.js
Child mini-css-extract-plugin ../node_modules/css-loader/dist/cjs.js!../node_modules/sass-loader/dist/cjs.js!app/static/css/index.scss:
    Entrypoint mini-css-extract-plugin = *
    [../node_modules/css-loader/dist/cjs.js!../node_modules/sass-loader/dist/cjs.js!./app/static/css/index.scss] 185 bytes {mini-css-extract-plugin} [built] [failed] [1 error]
    
    ERROR in ../node_modules/css-loader/dist/cjs.js!../node_modules/sass-loader/dist/cjs.js!./app/static/css/index.scss
    Module build failed: TypeError: this.getResolve is not a function
        at Object.loader (/home/jerryj/workspace/ethwall/node_modules/sass-loader/dist/index.js:52:26)

```

### Code

https://gist.github.com/jerryji/02731d7db5a91eff24a9c867cb220f56

### How Do We Reproduce?

IDK, do checkout this comment, which I concur -- https://github.com/webpack-contrib/sass-loader/issues/761#issuecomment-554608680

**Comment by evilebottnawi** [comment]
Update webpack to latest version https://github.com/webpack-contrib/sass-loader/blob/master/package.json#L38
