### ISSUE TITLE
TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received undefined

### ISSUE THREAD

**Issue by LP1994** [webpack-contrib/sass-loader#858]
" sass-loader@8.0.2 ”There was no mistake, “ sass-loader@9.0.0 ”Something went wrong.

      throw error;
      ^

TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received undefined
    at validateString (internal/validators.js:121:11)
    at Object.normalize (path.js:266:5)
    at G:\WebStormWS\WebProTpl\node_modules\sass-loader\dist\index.js:50:40
    at Function.call$2 (G:\WebStormWS\WebProTpl\node_modules\sass\sass.dart.js:88152:16)
    at _render_closure1.call$2 (G:\WebStormWS\WebProTpl\node_modules\sass\sass.dart.js:77579:12)
    at _RootZone.runBinary$3$3 (G:\WebStormWS\WebProTpl\node_modules\sass\sass.dart.js:26142:18)
    at _RootZone.runBinary$3 (G:\WebStormWS\WebProTpl\node_modules\sass\sass.dart.js:26146:19)
    at _FutureListener.handleError$1 (G:\WebStormWS\WebProTpl\node_modules\sass\sass.dart.js:24590:19)
    at _Future__propagateToListeners_handleError.call$0 (G:\WebStormWS\WebProTpl\node_modules\sass\sass.dart.js:24887:40)
    at Object._Future__propagateToListeners (G:\WebStormWS\WebProTpl\node_modules\sass\sass.dart.js:4311:88)
    at _Future._completeError$2 (G:\WebStormWS\WebProTpl\node_modules\sass\sass.dart.js:24715:9)
    at _Future__asyncCompleteError_closure.call$0 (G:\WebStormWS\WebProTpl\node_modules\sass\sass.dart.js:24810:18)
    at Object._microtaskLoop (G:\WebStormWS\WebProTpl\node_modules\sass\sass.dart.js:4361:21)
    at StaticClosure._startMicrotaskLoop (G:\WebStormWS\WebProTpl\node_modules\sass\sass.dart.js:4367:11)
    at _AsyncRun__scheduleImmediateJsOverride_internalCallback.call$0 (G:\WebStormWS\WebProTpl\node_modules\sass\sass.dart.js:24022:21)
    at invokeClosure (G:\WebStormWS\WebProTpl\node_modules\sass\sass.dart.js:1363:26) {
  dartException: UnknownJsTypeError {
    '__js_helper$_message': 'The "path" argument must be of type string. Received undefined',
    '$thrownJsError': TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received undefined
        at validateString (internal/validators.js:121:11)
        at Object.normalize (path.js:266:5)
        at G:\WebStormWS\WebProTpl\node_modules\sass-loader\dist\index.js:50:40
        at Function.call$2 (G:\WebStormWS\WebProTpl\node_modules\sass\sass.dart.js:88152:16)
        at _render_closure1.call$2 (G:\WebStormWS\WebProTpl\node_modules\sass\sass.dart.js:77579:12)
        at _RootZone.runBinary$3$3 (G:\WebStormWS\WebProTpl\node_modules\sass\sass.dart.js:26142:18)
        at _RootZone.runBinary$3 (G:\WebStormWS\WebProTpl\node_modules\sass\sass.dart.js:26146:19)
        at _FutureListener.handleError$1 (G:\WebStormWS\WebProTpl\node_modules\sass\sass.dart.js:24590:19)
        at _Future__propagateToListeners_handleError.call$0 (G:\WebStormWS\WebProTpl\node_modules\sass\sass.dart.js:24887:40)
        at Object._Future__propagateToListeners (G:\WebStormWS\WebProTpl\node_modules\sass\sass.dart.js:4311:88)
        at _Future._completeError$2 (G:\WebStormWS\WebProTpl\node_modules\sass\sass.dart.js:24715:9)
        at _Future__asyncCompleteError_closure.call$0 (G:\WebStormWS\WebProTpl\node_modules\sass\sass.dart.js:24810:18)
        at Object._microtaskLoop (G:\WebStormWS\WebProTpl\node_modules\sass\sass.dart.js:4361:21)
        at StaticClosure._startMicrotaskLoop (G:\WebStormWS\WebProTpl\node_modules\sass\sass.dart.js:4367:11)
        at _AsyncRun__scheduleImmediateJsOverride_internalCallback.call$0 (G:\WebStormWS\WebProTpl\node_modules\sass\sass.dart.js:24022:21)
        at invokeClosure (G:\WebStormWS\WebProTpl\node_modules\sass\sass.dart.js:1363:26) {
      code: 'ERR_INVALID_ARG_TYPE',
      '$cachedTrace': [_StackTrace]
    }
  }
}

**Comment by evilebottnawi** [comment]
@LP1994 Each time I ask you do not ignore the issue template, why do you ignore me? You do not respect someone else’s time?

**Comment by LP1994** [comment]
> @LP1994 Each time I ask you do not ignore the issue template, why do you ignore me? You do not respect someone else’s time?

Sorry, I didn't follow the question template. I'll fill in the details later.

**Comment by evilebottnawi** [comment]
@LP1994 In the near future, such problems will close automatically. And at the moment I will close it until you update the issue.

**Comment by evilebottnawi** [comment]
Fixed https://github.com/webpack-contrib/sass-loader/pull/860

**Comment by LP1994** [comment]
> Fixed #860

Thank you, I updated to the latest version of, successfully compiled through.
