### ISSUE TITLE
Update 10.0.1 leads to crash in vue.js application with export klona "do not define a valid './full' target"

### ISSUE THREAD

**Issue by borysl** [webpack-contrib/sass-loader#885]
- Operating System: Windows 10 Version 1809 (Build 17763.1397).
- Node Version: v13.5.0
- NPM Version: 6.13.4
- webpack Version: 4.44.1
- sass-loader Version: 10.0.1

I have build simple app from vue.js course from Pluralsight (upon request can share the code) and run into trouble

### Expected Behavior

Compiling and running app with no problem

### Actual Behavior

```
 ERROR  Failed to compile with 1 errors                                                                         16:15:51

 error  in ./src/build/RobotBuilder.vue?vue&type=style&index=0&id=1c5832ea&lang=scss&scoped=true&

Module build failed (from ./node_modules/sass-loader/dist/cjs.js):
Error: Package exports for 'C:\vue\build-a-bot\node_modules\klona' do not define a valid './full' target
    at resolveExportsTarget (internal/modules/cjs/loader.js:618:9)
    at applyExports (internal/modules/cjs/loader.js:499:14)
    at resolveExports (internal/modules/cjs/loader.js:548:12)
    at Function.Module._findPath (internal/modules/cjs/loader.js:654:22)
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:953:27)
    at Function.Module._load (internal/modules/cjs/loader.js:859:27)
    at Module.require (internal/modules/cjs/loader.js:1028:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (C:\vue\build-a-bot\node_modules\sass-loader\dist\utils.js:19:13)
    at Module._compile (internal/modules/cjs/loader.js:1139:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1159:10)
    at Module.load (internal/modules/cjs/loader.js:988:32)
    at Function.Module._load (internal/modules/cjs/loader.js:896:14)
    at Module.require (internal/modules/cjs/loader.js:1028:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (C:\vue\build-a-bot\node_modules\sass-loader\dist\index.js:16:14)

 @ ./node_modules/vue-style-loader??ref--8-oneOf-1-0!./node_modules/css-loader/dist/cjs.js??ref--8-oneOf-1-1!./node_modules/vue-loader/lib/loaders/stylePostLoader.js!./node_modules/postcss-loader/src??ref--8-oneOf-1-2!./node_modules/sass-loader/dist/cjs.js??ref--8-oneOf-1-3!./node_modules/cache-loader/dist/cjs.js??ref--0-0!./node_modules/vue-loader/lib??vue-loader-options!./src/build/RobotBuilder.vue?vue&type=style&index=0&id=1c5832ea&lang=scss&scoped=true& 4:14-467 14:3-18:5 15:22-475
 @ ./src/build/RobotBuilder.vue?vue&type=style&index=0&id=1c5832ea&lang=scss&scoped=true&
 @ ./src/build/RobotBuilder.vue
 @ ./node_modules/cache-loader/dist/cjs.js??ref--12-0!./node_modules/babel-loader/lib!./node_modules/cache-loader/dist/cjs.js??ref--0-0!./node_modules/vue-loader/lib??vue-loader-options!./src/App.vue?vue&type=script&lang=js&
 @ ./src/App.vue?vue&type=script&lang=js&
 @ ./src/App.vue
 @ ./src/main.js
 @ multi (webpack)-dev-server/client?http://192.168.1.110:8080/sockjs-node (webpack)/hot/dev-server.js ./src/main.js
```

### Code

Project is shared: https://gitlab.com/borysl/build-a-bot/-/tree/bug_in_sass-loader

### How Do We Reproduce?

npm install
npm run serve

### Workaround

Downgrade sass-loader to version 10.0.0

**Comment by evilebottnawi** [comment]
`v13.5.0` is buggy, please migrate on `node@14` or `node@12`, we can't fix it here, sorry

**Comment by borysl** [comment]
> `v13.5.0` is buggy, please migrate on `node@14` or `node@12`, we can't fix it here, sorry

Well, node@14.9.0 (npm 6.14.8) is not [supported by sass](https://github.com/sass/node-sass/releases/tag/v4.13.1) (at least not in windows and spews this error message

```
 error  in ./src/build/PartSelector.vue?vue&type=style&index=0&id=395d152c&lang=scss&scoped=true&

Module build failed (from ./node_modules/sass-loader/dist/cjs.js):
Error: Node Sass does not yet support your current environment: Windows 64-bit with Unsupported runtime (83)
For more information on which environments are supported please see:
https://github.com/sass/node-sass/releases/tag/v4.13.1
    at module.exports (C:\vue\build-a-bot\node_modules\node-sass\lib\binding.js:13:13)
    at Object.<anonymous> (C:\vue\build-a-bot\node_modules\node-sass\lib\index.js:14:35)
    at Module._compile (internal/modules/cjs/loader.js:1075:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1096:10)
    at Module.load (internal/modules/cjs/loader.js:940:32)
    at Function.Module._load (internal/modules/cjs/loader.js:781:14)
    at Module.require (internal/modules/cjs/loader.js:964:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at getDefaultSassImplementation (C:\vue\build-a-bot\node_modules\sass-loader\dist\utils.js:43:10)
    at getSassImplementation (C:\vue\build-a-bot\node_modules\sass-loader\dist\utils.js:57:30)
    at Object.loader (C:\vue\build-a-bot\node_modules\sass-loader\dist\index.js:34:59)

 @ ./node_modules/vue-style-loader??ref--8-oneOf-1-0!./node_modules/css-loader/dist/cjs.js??ref--8-oneOf-1-1!./node_modules/vue-loader/lib/loaders/stylePostLoader.js!./node_modules/postcss-loader/src??ref--8-oneOf-1-2!./node_modules/sass-loader/dist/cjs.js??ref--8-oneOf-1-3!./node_modules/cache-loader/dist/cjs.js??ref--0-0!./node_modules/vue-loader/lib??vue-loader-options!./src/build/PartSelector.vue?vue&type=style&index=0&id=395d152c&lang=scss&scoped=true& 4:14-467 14:3-18:5 15:22-475
 @ ./src/build/PartSelector.vue?vue&type=style&index=0&id=395d152c&lang=scss&scoped=true&
 @ ./src/build/PartSelector.vue
 @ ./node_modules/cache-loader/dist/cjs.js??ref--12-0!./node_modules/babel-loader/lib!./node_modules/cache-loader/dist/cjs.js??ref--0-0!./node_modules/vue-loader/lib??vue-loader-options!./src/build/RobotBuilder.vue?vue&type=script&lang=js&
 @ ./src/build/RobotBuilder.vue?vue&type=script&lang=js&
 @ ./src/build/RobotBuilder.vue
 @ ./src/router/index.js
 @ ./src/main.js
 @ multi (webpack)-dev-server/client?http://192.168.1.110:8080/sockjs-node (webpack)/hot/dev-server.js ./src/main.js
```

With version node@12.18.3 it was alright, however
```
 npm rebuild node-sass
```
was needed

**Comment by evilebottnawi** [comment]
Yes, you need to run ` npm rebuild node-sass` when you change node version, something else?

**Comment by evilebottnawi** [comment]
I want to close this issue, feel free to feedback
