### ISSUE TITLE
this.getOptions is not a function with node-sass 6.0.1

### ISSUE THREAD

**Issue by alexanderkogan** [webpack-contrib/sass-loader#974]
- Operating System: Manjaro Linux 21.0.7
- Node Version: 14.17.3
- NPM Version: 6.14.13
- webpack Version: 4.46.0
- sass-loader Version: 12.1.0
- node-sass Version: 6.0.1

### Expected Behavior

preact build finishes successfuly.

### Actual Behavior

Getting error on running `preact build`:
```
✖ ERROR ./style/index.scss
Module build failed (from ../node_modules/mini-css-extract-plugin/dist/loader.js):
ModuleBuildError: Module build failed (from ../node_modules/preact-cli/lib/lib/webpack/proxy-loader.js):
TypeError: this.getOptions is not a function
    at Object.loader (./node_modules/sass-loader/dist/index.js:25:24)
    at Object.proxyLoader (./node_modules/preact-cli/lib/lib/webpack/proxy-loader.js:28:32)
    at ./node_modules/webpack/lib/NormalModule.js:316:20
    at ./node_modules/loader-runner/lib/LoaderRunner.js:367:11
    at ./node_modules/loader-runner/lib/LoaderRunner.js:233:18
 @ ./index.js 1:0-17
```

### Code

```js
// webpack.config.js
// The one used by preact by default
```

### How Do We Reproduce?
We are using node-sass and already updated it to v6.0.1 before updating sass-loader.
sass-loader was on 10.2.0 and updating to 12.1.0 yielded the error.
There is another issue in node-sass with the same versions, but not much information otherwise: https://github.com/sass/node-sass/issues/3139

**Comment by alexanderkogan** [comment]
I'm stupid.

>  BREAKING CHANGES
> minimum supported webpack version is 5
